---
submariner:
  clusterId: ""
  token: ""
  clusterCidr: "10.42.0.0/16"
  serviceCidr: "10.43.0.0/16"
  globalCidr: ""
  natEnabled: false
  colorCodes: blue
  debug: false
  serviceDiscovery: false
crd:
  create: true
broker:
  type: k8s
  server: example.k8s.apiserver
  token: test
  namespace: xyz
  insecure: false
  ca: ""
rbac:
  create: true
ipsec:
  psk: ""
  debug: false
  ikePort: 500
  natPort: 4500
leadership:
  leaseDuration: 10
  renewDeadline: 5
  retryPeriod: 2
gateway:
  image:
    repository: quay.io/submariner/submariner-gateway
    tag: ""
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelectorEnabled: true
  nodeSelector: {}
  tolerations: []
  affinity: {}
routeAgent:
  image:
    repository: quay.io/submariner/submariner-route-agent
    tag: ""
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
globalnet:
  image:
    repository: quay.io/submariner/submariner-globalnet
    tag: ""
    pullPolicy: IfNotPresent
lighthouse:
  image:
    repository: quay.io/submariner/lighthouse-agent
    tag: ""
    pullPolicy: IfNotPresent
lighthouseCoredns:
  name: ""
  image:
    repository: quay.io/submariner/lighthouse-coredns
    tag: ""
    pullPolicy: IfNotPresent
serviceAccounts:
  gateway:
    create: true
    name: ""
  routeAgent:
    create: true
    name: ""
  globalnet:
    create: true
    name: ""
  lighthouseAgent:
    create: true
    name: ""
  lighthouseCoreDns:
    create: true
    name: ""
