---
extends: default
rules:
  comments:
    level: warning
  comments-indentation:
    level: warning
  line-length:
    max: 150
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    indent-sequences: consistent