{{- if .Values.crd.create -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.submariner.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: submariner.io
  version: v1
  names:
    kind: Cluster
    plural: clusters
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: endpoints.submariner.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: submariner.io
  version: v1
  names:
    kind: Endpoint
    plural: endpoints
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.submariner.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: submariner.io
  version: v1
  names:
    kind: Gateway
    plural: gateways
  scope: Namespaced
  additionalPrinterColumns:
    - name: ha-status
      type: string
      description: High Availability Status of the Gateway
      JSONPath: .status.haStatus
---
{{- if .Values.submariner.serviceDiscovery }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: multiclusterservices.lighthouse.submariner.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: lighthouse.submariner.io
  version: v1
  names:
    kind: MultiClusterService
    plural: multiclusterservices
    singular: multiclusterservice
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clusterServiceInfo:
              properties:
                clusterID:
                  type: "string"
                clusterDomain:
                  type: "string"
                serviceIP:
                  type: "string"
                port:
                  type: "integer"
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceexports.lighthouse.submariner.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: lighthouse.submariner.io
  version: v2alpha1
  names:
    kind: ServiceExport
    plural: serviceexports
    singular: serviceexport
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceimports.lighthouse.submariner.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: lighthouse.submariner.io
  version: v2alpha1
  names:
    kind: ServiceImport
    plural: serviceimports
    singular: serviceimport
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceexports.multicluster.x-k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: multicluster.x-k8s.io
  scope: Namespaced
  names:
    plural: serviceexports
    singular: serviceexport
    kind: ServiceExport
    shortNames:
      - svcex
  versions:
    - name: v1alpha1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceimports.multicluster.x-k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: multicluster.x-k8s.io
  scope: Namespaced
  names:
    plural: serviceimports
    singular: serviceimport
    kind: ServiceImport
    shortNames:
      - svcim
  versions:
    - name: v1alpha1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: Type
      type: string
      description: The type of this ServiceImport
      jsonPath: .spec.type
    - name: IP
      type: string
      description: The VIP for this ServiceImport
      jsonPath: .spec.ips
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
{{- end -}}
{{- end -}}